# Generated by Django 4.2.23 on 2026-05-18 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anomaly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anomaly_type', models.CharField(choices=[('high_amount', 'Unusually High Amount'), ('odd_hour', 'Transaction at Unusual Hour'), ('category_spike', 'Category Spending Spike'), ('unusual_frequency', 'Unusual Transaction Frequency')], max_length=30)),
                ('score', models.FloatField()),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomalies', to='transactions.transaction')),
            ],
            options={
                'db_table': 'anomalies',
                'ordering': ['-score'],
            },
        ),
    ]
